export enum OrganisationStatus {
  NEW = 'NEW',
  FREIGABE_KONTAKT_ORGANISATION = 'FREIGABE_KONTAKT_ORGANISATION',
  FREIGABE_CLEARING = 'FREIGABE_CLEARING',
  RUECKFRAGE_CLEARING = 'RUECKFRAGE_CLEARING',
  FREIGABE_VERWEIGERT_CLEARING = 'FREIGABE_VERWEIGERT_CLEARING',
  FREIGABE_VERWEIGERT_KONTAKT_INITIATIVE = 'FREIGABE_VERWEIGERT_KONTAKT_INITIATIVE',
  PRIVACY_CONSENT_REQUIRED = 'PRIVACY_CONSENT_REQUIRED',
  AKTUALISIERUNG_ORGANISATION = 'AKTUALISIERUNG_ORGANISATION'
}
