CREATE TABLE newsletter_subscriptions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_address    VARCHAR(255)                            NOT NULL,
    privacy_consent  BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    modified_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    last_modified_by VARCHAR(255),
    version          BIGINT,
    CONSTRAINT pk_newsletter_subscriptions PRIMARY KEY (id)
);

ALTER TABLE newsletter_subscriptions
    ADD CONSTRAINT uc_newsletter_subscriptions_email_address UNIQUE (email_address);
