drop table newsletter_subscriptions cascade;
drop table initiative_on_map_audit_log cascade;
drop table initiative_on_map_external_categories_audit_log cascade;
drop table initiative_on_map_rne_categories_audit_log cascade;
drop table initiative_on_map_sub_goals_audit_log cascade;
drop table initiative_on_map_sustainable_development_goals_audit_log cascade;
drop table initiative_on_map_external_categories cascade;
drop table initiative_on_map_rne_categories cascade;
drop table initiative_on_map_sub_goals cascade;
drop table initiative_on_map_sustainable_development_goals cascade;
drop table initiative_work_in_progress_external_categories cascade;
drop table initiative_work_in_progress_rne_categories cascade;
drop table initiative_work_in_progress cascade;
drop table initiative_on_map cascade;
drop table initiative_work_in_progress_sustainable_development_goals cascade;


