spring:
  application:
    name: wpgwn-app
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    # In Produktion auf false
    generate-ddl: false
    show-sql: false
    hibernate:
      # In Produktion auf validate oder none
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.type.preferred_duration_jdbc_type: BIGINT
      org.hibernate.envers.audit_table_suffix: _AUDIT_LOG
  messages:
    basename: i18n/message
  flyway:
    enabled: true
  mvc:
    log-resolved-exception: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/wpgwn-app
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB
      location: ${java.io.tmpdir}
      resolve-lazily: true

action-page:
  default-recipients: gemeinschaftswerk@nachhaltigkeitsrat.de

springdoc:
  swagger-ui:
    enabled: false
  default-produces-media-type:
    application/json
  packages-to-scan:
    - "com.exxeta.wpgwn.wpgwnapp.api.controller"
    - "com.exxeta.wpgwn.wpgwnapp.files"
server:
  port: 8080

wpgwn:
  cache:
    max-age: 30d
    cache-public: true
  feature-setting-url: '/items/features'
  organisation:
    dan-id: 0
    random-id-life-time: 5d
    reminder-email:
      cron: "-"
      max-reminders: 2
      duration-between-reminders: 7d
      batch-size: 250
    privacy-content-email-template: "email/organisation-work-in-progress/privacy-consent/organisation-privacy-consent.html"
    import-privacy-consent-email:
      cron: 0 0 0 * * *
    #      cron: 0/10 * * * * *
    duplicate:
      nameSimilarityThreshold: 0.7
    contactInvite:
      expireFromCreationInDays: 42
    organisationMembership:
      oneTimePasswordLength: 12
      expireFromCreationInDays: 42
    marketplace:
      max-offers: 30
      max-best-practises: 30
    dan:
      max-dans: 100
keycloak:
  admin:
    admin-realm: master
    connection-pool-size: 10
    read-timeout: 10
    connection-timeout: 10
nominatim:
  url: https://nominatim.openstreetmap.org

feign:
  client:
    config:
      cms-client:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
      nominatim-client:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
  httpclient:
    disable-ssl-validation: true
    enabled: false
  okhttp:
    enabled: true

