name: Maven Build and Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual workflow dispatch"
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean verify --file ${{ github.workspace }}/backend/pom.xml
